version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: biometric_web
    restart: always
    ports:
      - 9090:9090
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./:/app

  mysql:
    image: mysql:latest
    container_name: biometric_mysql
    command: mysqld --user=root
    cap_add:
      - SYS_NICE
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=showcase_db
      - MYSQL_USER=timely
      - MYSQL_PASSWORD=6ZpCj16&hs78DQ4+A
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

# Names our volume
volumes:
  db:
    driver: local